"""'pictures'

Revision ID: 3a1352aec4e9
Revises: b34d04012ad7
Create Date: 2019-02-01 00:33:24.828542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1352aec4e9'
down_revision = 'b34d04012ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('trip_picture', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('user_picture', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_picture')
    op.drop_column('trip', 'trip_picture')
    # ### end Alembic commands ###
