"""'prvi'

Revision ID: 7d23432e4824
Revises: b0028c33fd25
Create Date: 2019-01-28 14:37:55.034500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d23432e4824'
down_revision = 'b0028c33fd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('total_cost', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('transport', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_trip_total_cost'), 'trip', ['total_cost'], unique=False)
    op.create_index(op.f('ix_trip_transport'), 'trip', ['transport'], unique=False)
    op.drop_index('ix_trip_cost', table_name='trip')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'trip_rating')
    op.drop_column('trip', 'user_id')
    op.drop_column('trip', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('cost', sa.INTEGER(), nullable=True))
    op.add_column('trip', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('trip', sa.Column('trip_rating', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'])
    op.create_index('ix_trip_cost', 'trip', ['cost'], unique=False)
    op.drop_index(op.f('ix_trip_transport'), table_name='trip')
    op.drop_index(op.f('ix_trip_total_cost'), table_name='trip')
    op.drop_column('trip', 'transport')
    op.drop_column('trip', 'total_cost')
    # ### end Alembic commands ###
