"""empty message

Revision ID: cff2eb9bc1b7
Revises: 7e059969be9d
Create Date: 2019-01-30 18:10:34.657821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff2eb9bc1b7'
down_revision = '7e059969be9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('spol', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'spol')
    # ### end Alembic commands ###
